
platform :ios, ‘8.0’

target ‘表情键盘’ do
use_frameworks!

#pod 'BYStatistics', :git => "http://git.iqdnet.cn/qding-app/app-analytics-ios.git", :branch => 'develop', :tag => '1.0.0'

#pod 'Alamofire'     #, '~> 4.6.0'
#pod 'SnapKit'       #,'~> 4.0.0'
#pod 'SDWebImage'    #, '~> 4.2.3'
#pod 'SVProgressHUD' #, '~> 2.2.2'
pod 'YYModel'       #, '~> 1.0.4'
#pod 'pop'	    #, '~> 1.0.10'

end
